### PR TITLE
AUI-1367 Make aui-video accessible 

### PR DESCRIPTION
**Pull request by marclundgren**
Hey Mike. You can test this change by running :    `grunt build --src src/aui-audio`

### CODE REVIEW

**Comment by mjbradford89** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mjbradford89** [comment]
Is cda1cfe on the wrong branch?  Its' changes only pertain to the char-counter.

**Comment by marclundgren** [comment]
what commit? haha

**Comment by mjbradford89** [comment]
haha wow it's gone!

Merged and pushed to Jon: https://github.com/jonmak08/alloy-ui/pull/128

Thanks!

**Pull request closed without merging**
