### PR TITLE
AUI-1364 Make aui-toggler accessible 

### PR DESCRIPTION
**Pull request by marclundgren**
I DIDNT BREAK ANYTHING PROMISE

### CODE REVIEW

**Comment by mjbradford89** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by mjbradford89** [comment]
Hey Marc,

I'm not getting any audio feedback on the Toggler in the demo.  

Is that intentional? I get it on the Toggler Delegate demo.

**Comment by mjbradford89** [comment]
Also on the Toggler Delegate I don't get any 'expanded' feedback until it's been toggled at least once.

**Comment by marclundgren** [comment]
oh yikes. ok ill re-open https://github.com/marclundgren/alloy-ui/pull/38

**Comment by marclundgren** [comment]
> Also on the Toggler Delegate I don't get any 'expanded' feedback until it's been toggled at least once.

I noticed this is true for both Toggler and Toggler Delegate triggers

**Pull request closed without merging**
